[project]
name = "budgetvisulizer"
version = "0.1.0"
description = "Simple scripts to visualize monthly budgets"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dash>=4.0.0",
    "openpyxl>=3.1.5",
    "pandas>=3.0.1",
    "plotly>=6.6.0",
]

[tool.ruff]
target-version = "py313"
line-length = 100
exclude = [
    ".git",
    ".venv",
    "__pycache__",
    "build",
    "dist",
]

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "FBT001", # Boolean-typed positional argument in function definition
    "FBT002", # Boolean default positional argument in function definition
    "PLR0913", # Too many arguments in function definition
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false

[tool.pyright]
pythonVersion = "3.13"
typeCheckingMode = "standard"

include = ["."]
exclude = [
    "**/__pycache__",
    "**/.venv",
    "**/dist",
    "**/build",
    "**/node_modules",
    "**/.*"]

reportMissingImports = true